server:
  port: 7001

spring:
  application:
    name: gateway

  cloud:
    nacos:
      server-addr: 47.101.186.136:8848

    gateway:
      # 网关路由配置
      routes:
        # 路由id，自定义，只要唯一即可
        - id: order-service
          # 路由的目标地址，lb就是负载均衡，后面跟服务名称
          uri: lb://order-service
          # 路由断言，也就是判断请求是否符合路由规则的条件
          predicates:
            # 这个是按照路径匹配，只要以 /order/ 开头就符合要求
            - Path=/order/**
      default-filters:
        - AddRequestHeader=origin, gateway